### ISSUE TITLE
CMake Error when install auvlib to build docker image

### ISSUE THREAD

**Issue by xyp8023** [nilsbore/auvlib#27]
Hi, I am building a docker image based on ros. When I tried to install auvlib, there is a CMake Error at satge "RUN  cmake -DCMAKE_INSTALL_PREFIX=../install .. 	&& make -j4". 
The error massage is: 
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "mesh_map" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "mesh_map" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "align_map" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "align_map" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_embree" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "patch_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "patch_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "base_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "base_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "map_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "map_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "sss_gen_sim" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "sss_gen_sim" which requires target "igl_opengl_glfw" that is not in the export set.

When I used to install auvlib on my own ubuntu 16.04, I did not remember getting this error, but I don't know why it happened now when I tried to build a docker based on ubuntu and ros. 
My DockerFile is like this:

FROM ros:kinetic-ros-core-xenial
RUN git clone https://github.com/nilsbore/auvlib.git
WORKDIR auvlib
RUN mkdir -p build && apt-get update && apt-get install -y libcereal-dev libglfw3-dev libceres-dev libtinyxml2-dev \ 
	&& git submodule update --init 
WORKDIR libigl 
RUN git submodule update --init external/embree \
	&& git submodule update --init external/glfw 
WORKDIR ../build
RUN  apt-get update && apt-get install -y libopencv-dev
RUN  cmake -DCMAKE_INSTALL_PREFIX=../install .. \
	&& make -j4 
RUN make install 

kinetic-ros-core-xenial is provided by ros: https://github.com/osrf/docker_images/blob/1a1c56d93f309d10c412c6323db5791fc1b23d1b/ros/kinetic/ubuntu/xenial/ros-core/Dockerfile
Anyone knows what might be the solution? Thanks!

**Comment by xyp8023** [comment]
To add the whole message got from cmake: 


Step 9/11 : RUN  cmake -DCMAKE_INSTALL_PREFIX=../install .. 	&& make -j4
 ---> Running in 275be65a928d
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.12.0 installed in: /usr with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP]
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- CGAL not found.  Set the CGAL_DIR cmake variable or environment variable to the directory containing CGALConfig.cmake. This is either the binary directory where CGAL was configured or PREFIX/lib/CGAL for an installation.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MEX_COMPILER MX_LIBRARY ENG_LIBRARY) 
-- Could NOT find MOSEK (missing:  MOSEK_LIBRARIES MOSEK_INCLUDE_DIR) 
-- Found Threads: TRUE  
-- Creating target: igl::core
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Detecting default ISA:
-- Detecting default ISA: SSE2
-- Could NOT find GLUT (missing:  GLUT_glut_LIBRARY GLUT_INCLUDE_DIR) 
-- Creating target: igl::embree
-- Creating target: igl::opengl
-- Creating target: igl::opengl_glfw
-- Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- pybind11 v2.3.dev0
Pybind11: /auvlib/src/pybind11/include
-- cxxopts version 2.2.0
Python dir: 
-- Configuring done
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "mesh_map" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "mesh_map" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "align_map" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "align_map" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_embree" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "drape_mesh" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "patch_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "patch_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "base_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "base_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "map_draper" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "map_draper" which requires target "igl_opengl_glfw" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "sss_gen_sim" which requires target "igl_core" that is not in the export set.
CMake Error: install(EXPORT "BathyMapsConfig" ...) includes target "sss_gen_sim" which requires target "igl_opengl_glfw" that is not in the export set.
-- Generating done
-- Build files have been written to: /auvlib/build
The command '/bin/sh -c cmake -DCMAKE_INSTALL_PREFIX=../install .. 	&& make -j4' returned a non-zero code: 1

**Comment by xyp8023** [comment]
I've made it to build a docker image to install auvlib.

using "cmake -DCMAKE_INSTALL_PREFIX=../install .. || exit 0" could ignore those errors, and installing opencv-3.3.1 and opencv_contrib-3.3.1 work.

**Comment by nilsbore** [comment]
@xyp8023 This error should now be fixed since https://github.com/nilsbore/auvlib/pull/32 . Could you update the dockerfile to remove the workaround and check that it still works?

**Comment by xyp8023** [comment]
@nilsbore Yes, I updated the dockerfile, and tested it, the error indeed was fixed.
