### ISSUE TITLE
Clarify that auvlib.data_tools.all_data.match_attitude needs to be called in order to have proper roll and pitch information

### ISSUE THREAD

**Issue by MaxLarsson2** [nilsbore/auvlib#56]
Can we add to the documentation and maybe to the tutorial that  auvlib.data_tools.all_data.match_attitude needs to be called in order to have access to pitch and roll information at later stages?

**Comment by nilsbore** [comment]
Hi @MaxLarsson2 ! Yes, absolutely. You may consider adding it in the documentation [here](https://github.com/nilsbore/auvlib/blob/master/docs/all_data.rst) (see [this](https://github.com/nilsbore/auvlib/blob/master/docs/data_tools.rst
) for reference on how). You may also consider adding it to any examples you want. I will watch out for PRs.

**Comment by nilsbore** [comment]
This was fixed in https://github.com/nilsbore/auvlib/pull/57 , need to rebuild docs but closing.
