### ISSUE TITLE
Why do we discard the pings deeper than 40m when parsing the mbes data?

### ISSUE THREAD

**Issue by Viki-Xu** [nilsbore/auvlib#84]
In [https://github.com/nilsbore/auvlib/blob/master/src/data_tools/src/all_data.cpp#L258](url), pings deeper than 40m are discarded, which may result in failure to build a complete mesh map from Hugin datasets. Why do we keep that condition? Can @nilsbore remove it if it's not needed?

**Comment by nilsbore** [comment]
Fixed in https://github.com/nilsbore/auvlib/pull/85
